/*
   --------------------------------------
      Developed by
      Dileepa Bandara
      https://dileepabandara.github.io
      contact.dileepabandara@gmail.com
      ©dileepabandara.dev
      2020
   --------------------------------------
*/

package main;

import com.mysql.jdbc.Connection;
import dashboard.Home;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
/*import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;*/

/**
 *
 * @author DileepaBandara
 */
public class LoginPanel extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs =null;
    
    String appTitle = "Class Manager";
    int randomCode;
    
    
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        this.setTitle(appTitle);
        this.setResizable(false);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconLogo.png")));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginOption = new javax.swing.JPanel();
        welcome = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnRecover = new javax.swing.JButton();
        btnSignup1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnMainWinL = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        recover = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnBackLogin = new javax.swing.JButton();
        btnMainWinR = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        selectOption = new javax.swing.JPanel();
        btnRecAnsQ = new javax.swing.JButton();
        btnRecEmail = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        recoverSecAns = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        cmbRecQ = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        txtRecA = new javax.swing.JPasswordField();
        chBoxShowPassRecover = new javax.swing.JCheckBox();
        btnsecQback = new javax.swing.JButton();
        btnsecQconfirm = new javax.swing.JButton();
        txtRecID = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        recoverEmail = new javax.swing.JPanel();
        txtCode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnReqCode = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtREmail = new javax.swing.JTextField();
        btnReqCode1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        resetPass = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btnrecUpdate = new javax.swing.JButton();
        btnrecCancel = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txtROldPass = new javax.swing.JPasswordField();
        txtUpdatePass = new javax.swing.JPasswordField();
        chBoxShowPass4 = new javax.swing.JCheckBox();
        chBoxShowPass3 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        signup = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPass1 = new javax.swing.JPasswordField();
        txtSecurityAnswer = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        cmbSecQues = new javax.swing.JComboBox<>();
        chBoxShowPass2 = new javax.swing.JCheckBox();
        chBoxShowPass1 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        cmbClassName = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnMainWinS = new javax.swing.JButton();
        brnBackLogin = new javax.swing.JButton();
        btnCreateAcc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginOption.setPreferredSize(new java.awt.Dimension(1200, 700));
        LoginOption.setLayout(new java.awt.CardLayout());

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setMinimumSize(new java.awt.Dimension(1200, 800));
        welcome.setPreferredSize(new java.awt.Dimension(1200, 800));
        welcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(101, 101, 101));
        jLabel10.setText("Class Manager");
        welcome.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 740, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(101, 101, 101));
        btnLogin.setText("Log In");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSignup.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(101, 101, 101));
        btnSignup.setText("Sign Up");
        btnSignup.setBorder(null);
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignupMouseExited(evt);
            }
        });
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        welcome.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 480, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/logo@0.75x.png"))); // NOI18N
        welcome.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 660, 480));

        LoginOption.add(welcome, "card5");

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login.setFont(new java.awt.Font("Public Sans Medium", 0, 12)); // NOI18N
        login.setMinimumSize(new java.awt.Dimension(1200, 700));
        login.setPreferredSize(new java.awt.Dimension(1200, 700));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 101, 101));
        jLabel1.setText("Login");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 150, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(135, 135, 135));
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 135, 135), 1, true));

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(135, 135, 135));
        txtUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 135, 135), 1, true));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(101, 101, 101));
        jLabel5.setText("Username");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(101, 101, 101));
        jLabel7.setText("Password");

        btnLogin1.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(101, 101, 101));
        btnLogin1.setText("Login");
        btnLogin1.setBorder(null);
        btnLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogin1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogin1MouseExited(evt);
            }
        });
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addGap(0, 62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        login.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 550, 280));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(101, 101, 101));
        jLabel8.setText("Forgot password ?");

        btnRecover.setBackground(new java.awt.Color(255, 255, 255));
        btnRecover.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRecover.setForeground(new java.awt.Color(101, 101, 101));
        btnRecover.setText("Recover Account");
        btnRecover.setBorder(null);
        btnRecover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecoverMouseExited(evt);
            }
        });
        btnRecover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecoverActionPerformed(evt);
            }
        });

        btnSignup1.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSignup1.setForeground(new java.awt.Color(101, 101, 101));
        btnSignup1.setText("Signup");
        btnSignup1.setBorder(null);
        btnSignup1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignup1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignup1MouseExited(evt);
            }
        });
        btnSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(101, 101, 101));
        jLabel4.setText("Haven't account ?");

        btnMainWinL.setBackground(new java.awt.Color(255, 255, 255));
        btnMainWinL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMainWinL.setForeground(new java.awt.Color(101, 101, 101));
        btnMainWinL.setText("Back to main window");
        btnMainWinL.setBorder(null);
        btnMainWinL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMainWinL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMainWinLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMainWinLMouseExited(evt);
            }
        });
        btnMainWinL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainWinLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMainWinL, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecover, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnRecover, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMainWinL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        login.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 600, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Subjects.png"))); // NOI18N
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 480, 450));

        LoginOption.add(login, "card2");

        recover.setBackground(new java.awt.Color(255, 255, 255));
        recover.setMinimumSize(new java.awt.Dimension(1200, 700));
        recover.setPreferredSize(new java.awt.Dimension(1200, 700));
        recover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(101, 101, 101));
        jLabel11.setText("Recover Password");
        recover.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 480, 60));

        btnBackLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnBackLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBackLogin.setForeground(new java.awt.Color(101, 101, 101));
        btnBackLogin.setText("Back to Login");
        btnBackLogin.setBorder(null);
        btnBackLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackLoginMouseExited(evt);
            }
        });
        btnBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLoginActionPerformed(evt);
            }
        });
        recover.add(btnBackLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 190, 49));

        btnMainWinR.setBackground(new java.awt.Color(255, 255, 255));
        btnMainWinR.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMainWinR.setForeground(new java.awt.Color(101, 101, 101));
        btnMainWinR.setText("Back to main window");
        btnMainWinR.setBorder(null);
        btnMainWinR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMainWinR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMainWinRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMainWinRMouseExited(evt);
            }
        });
        btnMainWinR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainWinRActionPerformed(evt);
            }
        });
        recover.add(btnMainWinR, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, 280, 50));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.CardLayout());

        selectOption.setBackground(new java.awt.Color(255, 255, 255));
        selectOption.setMinimumSize(new java.awt.Dimension(450, 350));
        selectOption.setPreferredSize(new java.awt.Dimension(450, 350));
        selectOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRecAnsQ.setBackground(new java.awt.Color(255, 255, 255));
        btnRecAnsQ.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRecAnsQ.setForeground(new java.awt.Color(101, 101, 101));
        btnRecAnsQ.setText("Answer to security qustion");
        btnRecAnsQ.setBorder(null);
        btnRecAnsQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecAnsQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecAnsQMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecAnsQMouseExited(evt);
            }
        });
        btnRecAnsQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecAnsQActionPerformed(evt);
            }
        });
        selectOption.add(btnRecAnsQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 290, 50));

        btnRecEmail.setBackground(new java.awt.Color(255, 255, 255));
        btnRecEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRecEmail.setForeground(new java.awt.Color(101, 101, 101));
        btnRecEmail.setText("Recover by email");
        btnRecEmail.setBorder(null);
        btnRecEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecEmailMouseExited(evt);
            }
        });
        btnRecEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecEmailActionPerformed(evt);
            }
        });
        selectOption.add(btnRecEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 220, 50));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(101, 101, 101));
        jLabel28.setText("Select a option to recover account");
        selectOption.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jPanel7.add(selectOption, "card5");

        recoverSecAns.setBackground(new java.awt.Color(255, 255, 255));
        recoverSecAns.setMinimumSize(new java.awt.Dimension(450, 350));
        recoverSecAns.setPreferredSize(new java.awt.Dimension(450, 350));
        recoverSecAns.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(101, 101, 101));
        jLabel24.setText("What is your security question");
        recoverSecAns.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        cmbRecQ.setBackground(new java.awt.Color(255, 255, 255));
        cmbRecQ.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbRecQ.setForeground(new java.awt.Color(101, 101, 101));
        cmbRecQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your question", "My favourite subject?", "My pet name?", "My birthdate?", "My favourite teacher?", "My hobbie?" }));
        cmbRecQ.setToolTipText("Select your class");
        cmbRecQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recoverSecAns.add(cmbRecQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 290, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(101, 101, 101));
        jLabel26.setText("Give correct answer");
        recoverSecAns.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        txtRecA.setBackground(new java.awt.Color(255, 255, 255));
        txtRecA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRecA.setForeground(new java.awt.Color(101, 101, 101));
        txtRecA.setToolTipText("Re enter your password");
        txtRecA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        recoverSecAns.add(txtRecA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 330, 40));

        chBoxShowPassRecover.setBackground(new java.awt.Color(255, 255, 255));
        chBoxShowPassRecover.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chBoxShowPassRecover.setForeground(new java.awt.Color(101, 101, 101));
        chBoxShowPassRecover.setText("Show Answer");
        chBoxShowPassRecover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 101, 101), 1, true));
        chBoxShowPassRecover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chBoxShowPassRecover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBoxShowPassRecoverActionPerformed(evt);
            }
        });
        recoverSecAns.add(chBoxShowPassRecover, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 160, 30));

        btnsecQback.setBackground(new java.awt.Color(255, 255, 255));
        btnsecQback.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnsecQback.setForeground(new java.awt.Color(101, 101, 101));
        btnsecQback.setText("Back");
        btnsecQback.setBorder(null);
        btnsecQback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsecQback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsecQbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsecQbackMouseExited(evt);
            }
        });
        btnsecQback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsecQbackActionPerformed(evt);
            }
        });
        recoverSecAns.add(btnsecQback, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 110, 50));

        btnsecQconfirm.setBackground(new java.awt.Color(255, 255, 255));
        btnsecQconfirm.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnsecQconfirm.setForeground(new java.awt.Color(101, 101, 101));
        btnsecQconfirm.setText("Confirm");
        btnsecQconfirm.setBorder(null);
        btnsecQconfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsecQconfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsecQconfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsecQconfirmMouseExited(evt);
            }
        });
        btnsecQconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsecQconfirmActionPerformed(evt);
            }
        });
        recoverSecAns.add(btnsecQconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 110, 50));

        txtRecID.setBackground(new java.awt.Color(255, 255, 255));
        txtRecID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        recoverSecAns.add(txtRecID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 290, 40));

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(101, 101, 101));
        jLabel30.setText("What is your ID");
        recoverSecAns.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 190, -1));

        jPanel7.add(recoverSecAns, "card3");

        recoverEmail.setBackground(new java.awt.Color(255, 255, 255));
        recoverEmail.setPreferredSize(new java.awt.Dimension(450, 350));
        recoverEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCode.setBackground(new java.awt.Color(255, 255, 255));
        txtCode.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCode.setMinimumSize(new java.awt.Dimension(14, 22));
        recoverEmail.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 220, 40));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(101, 101, 101));
        jLabel9.setText("Enter your registerd email");
        recoverEmail.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        btnReqCode.setBackground(new java.awt.Color(255, 255, 255));
        btnReqCode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnReqCode.setForeground(new java.awt.Color(101, 101, 101));
        btnReqCode.setText("Request secuirty code");
        btnReqCode.setBorder(null);
        btnReqCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReqCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqCodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqCodeMouseExited(evt);
            }
        });
        btnReqCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqCodeActionPerformed(evt);
            }
        });
        recoverEmail.add(btnReqCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 260, 60));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(101, 101, 101));
        jLabel23.setText("Enter security code");
        recoverEmail.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        txtREmail.setBackground(new java.awt.Color(255, 255, 255));
        txtREmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        recoverEmail.add(txtREmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 410, 40));

        btnReqCode1.setBackground(new java.awt.Color(255, 255, 255));
        btnReqCode1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnReqCode1.setForeground(new java.awt.Color(101, 101, 101));
        btnReqCode1.setText("Verify");
        btnReqCode1.setBorder(null);
        btnReqCode1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReqCode1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqCode1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqCode1MouseExited(evt);
            }
        });
        btnReqCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqCode1ActionPerformed(evt);
            }
        });
        recoverEmail.add(btnReqCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 150, 60));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(101, 101, 101));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        recoverEmail.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 120, 60));

        jPanel7.add(recoverEmail, "card3");

        resetPass.setBackground(new java.awt.Color(255, 255, 255));
        resetPass.setMinimumSize(new java.awt.Dimension(450, 350));
        resetPass.setPreferredSize(new java.awt.Dimension(450, 350));
        resetPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(101, 101, 101));
        jLabel27.setText("Create New Password");
        resetPass.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 210, -1));

        btnrecUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnrecUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnrecUpdate.setForeground(new java.awt.Color(101, 101, 101));
        btnrecUpdate.setText("Update");
        btnrecUpdate.setBorder(null);
        btnrecUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnrecUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnrecUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnrecUpdateMouseExited(evt);
            }
        });
        btnrecUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecUpdateActionPerformed(evt);
            }
        });
        resetPass.add(btnrecUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 130, 50));

        btnrecCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnrecCancel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnrecCancel.setForeground(new java.awt.Color(101, 101, 101));
        btnrecCancel.setText("Cancel");
        btnrecCancel.setBorder(null);
        btnrecCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnrecCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnrecCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnrecCancelMouseExited(evt);
            }
        });
        btnrecCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecCancelActionPerformed(evt);
            }
        });
        resetPass.add(btnrecCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 130, 50));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(101, 101, 101));
        jLabel29.setText("Your old password");
        resetPass.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, -1));

        txtROldPass.setBackground(new java.awt.Color(255, 255, 255));
        resetPass.add(txtROldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 280, 40));

        txtUpdatePass.setBackground(new java.awt.Color(255, 255, 255));
        resetPass.add(txtUpdatePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 280, 40));

        chBoxShowPass4.setBackground(new java.awt.Color(255, 255, 255));
        chBoxShowPass4.setForeground(new java.awt.Color(101, 101, 101));
        chBoxShowPass4.setText("Show Password");
        chBoxShowPass4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBoxShowPass4ActionPerformed(evt);
            }
        });
        resetPass.add(chBoxShowPass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        chBoxShowPass3.setBackground(new java.awt.Color(255, 255, 255));
        chBoxShowPass3.setForeground(new java.awt.Color(101, 101, 101));
        chBoxShowPass3.setText("Show Password");
        chBoxShowPass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBoxShowPass3ActionPerformed(evt);
            }
        });
        resetPass.add(chBoxShowPass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jPanel7.add(resetPass, "card4");

        recover.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 550, 580));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/2.png"))); // NOI18N
        recover.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        LoginOption.add(recover, "card4");

        signup.setBackground(new java.awt.Color(255, 255, 255));
        signup.setMinimumSize(new java.awt.Dimension(1200, 700));
        signup.setPreferredSize(new java.awt.Dimension(1200, 700));
        signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(101, 101, 101));
        jLabel13.setText("Class name");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(101, 101, 101));
        jLabel12.setText("First name");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(101, 101, 101));
        jLabel19.setText("Last name");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(101, 101, 101));
        jLabel18.setText("Age");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(101, 101, 101));
        jLabel15.setText("Security question");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(101, 101, 101));
        jLabel16.setText("Password");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(101, 101, 101));
        jLabel17.setText("Email");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        txtFName.setBackground(new java.awt.Color(255, 255, 255));
        txtFName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtFName.setForeground(new java.awt.Color(101, 101, 101));
        txtFName.setToolTipText("Enter your first name");
        txtFName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });
        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFNameKeyTyped(evt);
            }
        });
        jPanel6.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 290, -1));

        txtLName.setBackground(new java.awt.Color(255, 255, 255));
        txtLName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLName.setForeground(new java.awt.Color(101, 101, 101));
        txtLName.setToolTipText("Enter your last name");
        txtLName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLNameKeyTyped(evt);
            }
        });
        jPanel6.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 290, -1));

        txtAge.setBackground(new java.awt.Color(255, 255, 255));
        txtAge.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(101, 101, 101));
        txtAge.setToolTipText("Enter your age");
        txtAge.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });
        jPanel6.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 290, -1));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(101, 101, 101));
        txtEmail.setToolTipText("Enter your email");
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel6.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 290, -1));

        txtPass1.setBackground(new java.awt.Color(255, 255, 255));
        txtPass1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPass1.setForeground(new java.awt.Color(101, 101, 101));
        txtPass1.setToolTipText("Enter strong type password");
        txtPass1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPass1KeyTyped(evt);
            }
        });
        jPanel6.add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 220, -1));

        txtSecurityAnswer.setBackground(new java.awt.Color(255, 255, 255));
        txtSecurityAnswer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSecurityAnswer.setForeground(new java.awt.Color(101, 101, 101));
        txtSecurityAnswer.setToolTipText("Re enter your password");
        txtSecurityAnswer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel6.add(txtSecurityAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 220, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(101, 101, 101));
        jLabel22.setText("Mobile");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtMobile.setBackground(new java.awt.Color(255, 255, 255));
        txtMobile.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMobile.setForeground(new java.awt.Color(101, 101, 101));
        txtMobile.setToolTipText("Enter your email");
        txtMobile.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileKeyTyped(evt);
            }
        });
        jPanel6.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 290, -1));

        cmbSecQues.setBackground(new java.awt.Color(255, 255, 255));
        cmbSecQues.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbSecQues.setForeground(new java.awt.Color(101, 101, 101));
        cmbSecQues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your question", "My favourite subject?", "My pet name?", "My birthdate?", "My favourite teacher?", "My hobbie?" }));
        cmbSecQues.setToolTipText("Select your class");
        cmbSecQues.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(cmbSecQues, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 290, -1));

        chBoxShowPass2.setBackground(new java.awt.Color(255, 255, 255));
        chBoxShowPass2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chBoxShowPass2.setForeground(new java.awt.Color(101, 101, 101));
        chBoxShowPass2.setText("Show Answer");
        chBoxShowPass2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 101, 101), 1, true));
        chBoxShowPass2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chBoxShowPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBoxShowPass2ActionPerformed(evt);
            }
        });
        jPanel6.add(chBoxShowPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 430, 160, 30));

        chBoxShowPass1.setBackground(new java.awt.Color(255, 255, 255));
        chBoxShowPass1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chBoxShowPass1.setForeground(new java.awt.Color(101, 101, 101));
        chBoxShowPass1.setText("Show Password");
        chBoxShowPass1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 101, 101), 1, true));
        chBoxShowPass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chBoxShowPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBoxShowPass1ActionPerformed(evt);
            }
        });
        jPanel6.add(chBoxShowPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 310, 180, 30));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(101, 101, 101));
        jLabel25.setText("Answer");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        cmbClassName.setBackground(new java.awt.Color(255, 255, 255));
        cmbClassName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbClassName.setForeground(new java.awt.Color(101, 101, 101));
        cmbClassName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your class", "Bio", "Maths", "Agri", "ICT" }));
        cmbClassName.setToolTipText("Select your class");
        cmbClassName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(cmbClassName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 230, -1));

        signup.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 480));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 101, 101));
        jLabel3.setText("Create an account");
        signup.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 440, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/signup.png"))); // NOI18N
        signup.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 530, 400));

        btnMainWinS.setBackground(new java.awt.Color(255, 255, 255));
        btnMainWinS.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMainWinS.setForeground(new java.awt.Color(101, 101, 101));
        btnMainWinS.setText("Back to main window");
        btnMainWinS.setBorder(null);
        btnMainWinS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMainWinS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMainWinSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMainWinSMouseExited(evt);
            }
        });
        btnMainWinS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainWinSActionPerformed(evt);
            }
        });
        signup.add(btnMainWinS, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 230, 60));

        brnBackLogin.setBackground(new java.awt.Color(255, 255, 255));
        brnBackLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        brnBackLogin.setForeground(new java.awt.Color(101, 101, 101));
        brnBackLogin.setText("Back to Login");
        brnBackLogin.setBorder(null);
        brnBackLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brnBackLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brnBackLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brnBackLoginMouseExited(evt);
            }
        });
        brnBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnBackLoginActionPerformed(evt);
            }
        });
        signup.add(brnBackLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 160, 60));

        btnCreateAcc.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateAcc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCreateAcc.setForeground(new java.awt.Color(101, 101, 101));
        btnCreateAcc.setText("Create account");
        btnCreateAcc.setBorder(null);
        btnCreateAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateAccMouseExited(evt);
            }
        });
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });
        signup.add(btnCreateAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 170, 60));

        LoginOption.add(signup, "card3");

        jPanel1.add(LoginOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        setSize(new java.awt.Dimension(1218, 747));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecoverActionPerformed
        login.setVisible(false);
        signup.setVisible(false);
        recover.setVisible(true);
        welcome.setVisible(false);
        
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnRecoverActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        login.setVisible(false);
        signup.setVisible(true);
        recover.setVisible(false);
        welcome.setVisible(false);
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login.setVisible(true);
        signup.setVisible(false);
        recover.setVisible(false);
        welcome.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnMainWinSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainWinSActionPerformed
        login.setVisible(false);
        signup.setVisible(false);
        recover.setVisible(false);
        welcome.setVisible(true);
        
        cleanApplicationData();
        
    }//GEN-LAST:event_btnMainWinSActionPerformed

    private void btnMainWinLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainWinLActionPerformed
        login.setVisible(false);
        signup.setVisible(false);
        recover.setVisible(false);
        welcome.setVisible(true);
        
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnMainWinLActionPerformed

    private void btnMainWinRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainWinRActionPerformed
        login.setVisible(false);
        signup.setVisible(false);
        recover.setVisible(false);
        welcome.setVisible(true);
    }//GEN-LAST:event_btnMainWinRActionPerformed

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        login.setVisible(false);
        signup.setVisible(true);
        recover.setVisible(false);
        welcome.setVisible(false);
        
        txtUsername.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnSignup1ActionPerformed

    public void sendLoggerID(){
         String loggerID = txtUsername.getText();
    } 
   
    
    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        /*String username;
        String password;
        
        username = txtUsername.getText();
        password = txtPassword.getText();
        
        if (username.equals("1") && password.equals("1")){
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
        } else {
        JOptionPane.showMessageDialog(null, "Enter valid username and password");
        }*/

        String query = "SELECT * FROM account Where id=? and password=?";
        try{
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/classmanager","root","");
        pstmt=conn.prepareStatement(query);
        pstmt.setString(1, txtUsername.getText());
        pstmt.setString(2, txtPassword.getText());
        rs=pstmt.executeQuery();
        if(rs.next()){
            JOptionPane.showMessageDialog(null, "Login Successfully");
            Home home = new Home();
            home.setVisible(true);
            welcome w = new welcome();
            w.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "username or password do not match");
        }

        } catch (SQLException ex) {
            //Logger.getLogger(Forgot.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        
        txtUsername.setText("");
        txtPassword.setText("");
        
        
        
    }//GEN-LAST:event_btnLogin1ActionPerformed

    public void cleanLoginData(){
        txtUsername.setText("");
        txtPassword.setText("");
    }
    
    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLoginActionPerformed
        login.setVisible(true);
        signup.setVisible(false);
        recover.setVisible(false);
        welcome.setVisible(false);
    }//GEN-LAST:event_btnBackLoginActionPerformed

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void brnBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnBackLoginActionPerformed
        login.setVisible(true);
        signup.setVisible(false);
        recover.setVisible(false);
        welcome.setVisible(false);
        
        cleanApplicationData();
    }//GEN-LAST:event_brnBackLoginActionPerformed

    public void cleanApplicationData(){
        txtFName.setText("");
        txtLName.setText("");
        txtAge.setText("");
        txtEmail.setText("");
        txtMobile.setText("");
        cmbSecQues.setSelectedIndex(0);
        txtPass1.setText("");
        txtSecurityAnswer.setText("");
    }
    
    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
       btnLogin.setBackground(new Color(0, 125, 250));
       btnLogin.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setBackground(new Color(255, 255, 255));
        btnLogin.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseEntered
        btnSignup.setBackground(new Color(0, 125, 250));
        btnSignup.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnSignupMouseEntered

    private void btnSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseExited
        btnSignup.setBackground(new Color(255, 255, 255));
        btnSignup.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnSignupMouseExited

    
    public void createAccount(){
        try{
            String query = "INSERT INTO `account`(`fName`, `lName`, `age`, `email`, `mobile`, `className`, `password`, `secQuestion`, `secAnswer`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/classmanager", "root", "");
            pstmt=conn.prepareStatement(query);
            pstmt.setString(1, txtFName.getText());
            pstmt.setString(2, txtLName.getText());
            pstmt.setString(3, txtAge.getText());
            pstmt.setString(4, txtEmail.getText());
            pstmt.setString(5, txtMobile.getText());
            pstmt.setString(6, cmbClassName.getSelectedItem().toString());
            //pstmt.setString(6, txtClassName.getText());
            pstmt.setString(7, txtPass1.getText());
            pstmt.setString(8, cmbSecQues.getSelectedItem().toString());
            pstmt.setString(9, txtSecurityAnswer.getText());
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "REGISTER SUCCESSFULLY");


            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            }
    }
    
    public static boolean lengthCheck(String in, int min, int max){
        return max > in.length() || in.length() > min;
    }
    
    public void validateAccountRegister(){
        String fName = txtFName.getText();
        String lName = txtLName.getText();
        String age = txtAge.getText();
        String email = txtEmail.getText();
        String mobile = txtMobile.getText();
        String className = cmbClassName.getSelectedItem().toString();
        String secQuestion = cmbSecQues.getSelectedItem().toString();
        String pass1 = txtPass1.getText();
        String secAnswer = txtSecurityAnswer.getText();
        
        String gmailPattern = "^[a-zA-Z0-9]{1,30}@[a-zA-Z0-9]{1,20}.[a-zA-Z]{2,3}$";
        Pattern pattern = Pattern.compile(gmailPattern);
        Matcher regexMatcher = pattern.matcher(email);
        
        //String EMAIL_PATTERN = "^[a-zA-Z0-9]{1,30}@[a-zA-Z0-9]{1,20}.[a-zA-Z]{2,3}$";
        
        int minLength = 10;
        int maxLength = 10;
        
        
        if (fName.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter first name");
        } else if (lName.equals("")){
            JOptionPane.showMessageDialog(null, "Enter last name");
        }
        else if (age.equals("")){
            JOptionPane.showMessageDialog(null, "Enter age");
        }
        else if (email.equals("")){
            JOptionPane.showMessageDialog(null, "Enter email");
        }
        else if (!regexMatcher.matches()){
            JOptionPane.showMessageDialog(null, "Email format is not correct. Please use your gmail to register");
        }
        else if (mobile.equals("")){
            JOptionPane.showMessageDialog(null, "Enter mobile number");
        }
        else if (lengthCheck(mobile,minLength,maxLength)){
             JOptionPane.showMessageDialog(null, "Enter 10 digt mobile");
        }
        else if (className.equals("Select your class")){
            JOptionPane.showMessageDialog(null, "Select class name");
        }
        else if (pass1.equals("")){
            JOptionPane.showMessageDialog(null, "Enter password");
        }
        else if (pass1.length() <8 || pass1.length() >20) {
            JOptionPane.showMessageDialog(null, "Enter password between 8 - 20");
        }
        else if (secQuestion.equals("Select your question")){
            JOptionPane.showMessageDialog(null, "Select seurity question");
        }
        else if (secAnswer.equals("")){
            JOptionPane.showMessageDialog(null, "Enter answer");
        }
        else {
            JOptionPane.showMessageDialog(null, "No mistakes");
            createAccount();
            Home h2 = new Home();
            h2.setVisible(true);
            this.dispose();
        }
        
    }
   
    
    /*public void showID(){
    
            String query = "SELECT * FROM  account WHERE id = ' "+userId+" ' ";
            java.sql.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/classmanager", "root", "");
            PreparedStatement s =conn.prepareStatement(query);
            ResultSet rs = s.executeQuery(query);
            
            if (rs.next()) {
                 String profileUserID = rs.getString(1);
                 String profileFName = rs.getString(2);
                 String profileLName = rs.getString(3);
                 String profileAge = rs.getString(4);
                 String profileEmail = rs.getString(5);
                 String profileMobile = rs.getString(6);
                 String profileClassName = rs.getString(7);

        } catch (SQLException ex) {
            //Logger.getLogger(Forgot.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    
    }*/
    
    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        
        
         //showID();
        
        validateAccountRegister();
        
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnLogin1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin1MouseEntered
        btnLogin1.setBackground(new Color(0, 125, 250));
        btnLogin1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnLogin1MouseEntered

    private void btnLogin1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin1MouseExited
        btnLogin1.setBackground(new Color(255, 255, 255));
        btnLogin1.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnLogin1MouseExited

    private void btnSignup1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup1MouseEntered
        btnSignup1.setBackground(new Color(0, 125, 250));
        btnSignup1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnSignup1MouseEntered

    private void btnSignup1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup1MouseExited
        btnSignup1.setBackground(new Color(255, 255, 255));
        btnSignup1.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnSignup1MouseExited

    private void btnRecoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecoverMouseEntered
        btnRecover.setBackground(new Color(0, 125, 250));
        btnRecover.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnRecoverMouseEntered

    private void btnRecoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecoverMouseExited
        btnRecover.setBackground(new Color(255, 255, 255));
        btnRecover.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnRecoverMouseExited

    private void btnMainWinLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainWinLMouseEntered
        btnMainWinL.setBackground(new Color(0, 125, 250));
        btnMainWinL.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMainWinLMouseEntered

    private void btnMainWinLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainWinLMouseExited
        btnMainWinL.setBackground(new Color(255, 255, 255));
        btnMainWinL.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnMainWinLMouseExited

    private void btnMainWinRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainWinRMouseEntered
        btnMainWinR.setBackground(new Color(0, 125, 250));
        btnMainWinR.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMainWinRMouseEntered

    private void btnMainWinRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainWinRMouseExited
         btnMainWinR.setBackground(new Color(255, 255, 255));
        btnMainWinR.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnMainWinRMouseExited

    private void btnBackLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLoginMouseEntered
        btnBackLogin.setBackground(new Color(0, 125, 250));
        btnBackLogin.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnBackLoginMouseEntered

    private void btnBackLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLoginMouseExited
         btnBackLogin.setBackground(new Color(255, 255, 255));
        btnBackLogin.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnBackLoginMouseExited

    private void btnCreateAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAccMouseEntered
         btnCreateAcc.setBackground(new Color(0, 125, 250));
        btnCreateAcc.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnCreateAccMouseEntered

    private void btnCreateAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAccMouseExited
        btnCreateAcc.setBackground(new Color(255, 255, 255));
        btnCreateAcc.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnCreateAccMouseExited

    private void btnMainWinSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainWinSMouseEntered
        btnMainWinS.setBackground(new Color(0, 125, 250));
        btnMainWinS.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnMainWinSMouseEntered

    private void btnMainWinSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainWinSMouseExited
        btnMainWinS.setBackground(new Color(255, 255, 255));
        btnMainWinS.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnMainWinSMouseExited

    private void brnBackLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brnBackLoginMouseEntered
        brnBackLogin.setBackground(new Color(0, 125, 250));
        brnBackLogin.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_brnBackLoginMouseEntered

    private void brnBackLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brnBackLoginMouseExited
        brnBackLogin.setBackground(new Color(255, 255, 255));
        brnBackLogin.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_brnBackLoginMouseExited

    private void btnReqCodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqCodeMouseEntered
        btnReqCode.setBackground(new Color(0, 125, 250));
        btnReqCode.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnReqCodeMouseEntered

    private void btnReqCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqCodeMouseExited
        btnReqCode.setBackground(new Color(255, 255, 255));
        btnReqCode.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnReqCodeMouseExited

    private void btnReqCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqCodeActionPerformed
        /* try{
                Random rand = new Random();
                randomCode=rand.nextInt(999999);
                String host = "smtp.gmail.com";
                String user ="adepvt2@gmail.com";
                String pass="ade2ade2ade2";
                String to = txtREmail.getText();
                String subject="Reseting Code";
                String message ="Your reset code is "+randomCode;
                boolean sessionDebug = false;
                
                Properties pros = System.getProperties();
                pros.put("mail.smtp.starttls.enable", "true");
                pros.put("mail.smtp.host", "host");
                pros.put("mail.smtp.port","587");
                pros.put("mail.smtp.auth","true");
                pros.put("mail.smtp.starttls.required", "true");
                java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
                Session mailSession = Session.getDefaultInstance(pros, null);
                mailSession.setDebug(sessionDebug);
                Message msg = new MimeMessage(mailSession);
                msg.setFrom(new InternetAddress(user));
                InternetAddress [] address = {new InternetAddress(to)};
                msg.setRecipients(Message.RecipientType.TO, address);
                msg.setSubject(subject);
                msg.setText(message);
                Transport transport = mailSession.getTransport("smtp");
                transport.connect(host, user, pass);
                transport.sendMessage(msg, msg.getAllRecipients());
                transport.close();
                JOptionPane.showMessageDialog(null, "code has been send to the email");
                
         }catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, ex);
         }*/
    }//GEN-LAST:event_btnReqCodeActionPerformed

    private void txtMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyTyped
        char c = evt.getKeyChar();
        if (! (Character.isDigit(c) || (c ==KeyEvent.VK_BACK_SPACE) || c== KeyEvent.VK_DELETE) ) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMobileKeyTyped

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
       char c = evt.getKeyChar();
        if (! (Character.isDigit(c) || (c ==KeyEvent.VK_BACK_SPACE) || c== KeyEvent.VK_DELETE) ) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAgeKeyTyped

    private void txtFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyTyped
        char c = evt.getKeyChar();
        if (! (Character.isLetter(c) || (Character.isWhitespace(c)) || Character.isISOControl(c)) ) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtFNameKeyTyped

    private void chBoxShowPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBoxShowPass1ActionPerformed
        
        if (chBoxShowPass1.isSelected()) {
            txtPass1.setEchoChar((char) 0);
        } else {
            txtPass1.setEchoChar('*');
        }
    }//GEN-LAST:event_chBoxShowPass1ActionPerformed

    private void chBoxShowPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBoxShowPass2ActionPerformed
        if (chBoxShowPass2.isSelected()) {
            txtSecurityAnswer.setEchoChar((char) 0);
        } else {
            txtSecurityAnswer.setEchoChar('*');
        }
    }//GEN-LAST:event_chBoxShowPass2ActionPerformed

    private void txtLNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyTyped
        char c = evt.getKeyChar();
        if (! (Character.isLetter(c) || (Character.isWhitespace(c)) || Character.isISOControl(c)) ) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtLNameKeyTyped

    private void txtPass1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPass1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass1KeyTyped

    private void chBoxShowPassRecoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBoxShowPassRecoverActionPerformed
        if (chBoxShowPassRecover.isSelected()) {
            txtRecA.setEchoChar((char) 0);
        } else {
            txtRecA.setEchoChar('*');
        }
    }//GEN-LAST:event_chBoxShowPassRecoverActionPerformed

    private void btnsecQbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsecQbackMouseEntered
        btnsecQback.setBackground(new Color(0, 125, 250));
        btnsecQback.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnsecQbackMouseEntered

    private void btnsecQbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsecQbackMouseExited
        btnsecQback.setBackground(new Color(255, 255, 255));
        btnsecQback.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnsecQbackMouseExited

    private void btnsecQbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsecQbackActionPerformed
        recoverSecAns.setVisible(false);
        recoverEmail.setVisible(false);
        selectOption.setVisible(true);
        resetPass.setVisible(false);
        
        txtRecID.setText("");
        cmbRecQ.setSelectedIndex(0);
        txtRecA.setText("");
    }//GEN-LAST:event_btnsecQbackActionPerformed

    private void btnsecQconfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsecQconfirmMouseEntered
        btnsecQconfirm.setBackground(new Color(0, 125, 250));
        btnsecQconfirm.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnsecQconfirmMouseEntered

    private void btnsecQconfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsecQconfirmMouseExited
        btnsecQconfirm.setBackground(new Color(255, 255, 255));
        btnsecQconfirm.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnsecQconfirmMouseExited

    
    public void selectOldPass(){
    try {
            String userId = txtRecID.getText();
            String query = "SELECT * FROM  account WHERE id = ' "+userId+" ' ";
            java.sql.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/classmanager", "root", "");
            PreparedStatement s =conn.prepareStatement(query);
            ResultSet rs = s.executeQuery(query);
            
            if (rs.next()) {
                 String oldPass = rs.getString(8);
                 txtROldPass.setText(oldPass);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    private void btnsecQconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsecQconfirmActionPerformed
        
        
            String query = "SELECT * FROM account Where id=? and secAnswer=?";
            try{
            conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/classmanager","root","");
            pstmt=conn.prepareStatement(query);
            pstmt.setString(1, txtRecID.getText());
            pstmt.setString(2, txtRecA.getText());
            rs=pstmt.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Correct Details");
                recoverSecAns.setVisible(false);
                recoverEmail.setVisible(false);
                selectOption.setVisible(false);
                resetPass.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "username or password do not match");
            }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        
            selectOldPass();
        
    }//GEN-LAST:event_btnsecQconfirmActionPerformed

    private void btnrecUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrecUpdateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrecUpdateMouseEntered

    private void btnrecUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrecUpdateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrecUpdateMouseExited

    private void btnrecUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecUpdateActionPerformed
       
        try {
            String userId = txtRecID.getText();
            String query = "UPDATE account SET password =' "+txtUpdatePass.getText()+" ' WHERE id = ' "+userId+" ' ";
            java.sql.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/classmanager", "root", "");
            PreparedStatement pstm =conn.prepareStatement(query);
            pstm.execute();
           JOptionPane.showMessageDialog(null, "Your account updated");
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        
        recoverSecAns.setVisible(false);
        recoverEmail.setVisible(false);
        selectOption.setVisible(false);
        resetPass.setVisible(false);
        welcome.setVisible(true);
    }//GEN-LAST:event_btnrecUpdateActionPerformed

    private void btnrecCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrecCancelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrecCancelMouseEntered

    private void btnrecCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrecCancelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrecCancelMouseExited

    private void btnrecCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecCancelActionPerformed
        recoverSecAns.setVisible(false);
        recoverEmail.setVisible(false);
        selectOption.setVisible(true);
        resetPass.setVisible(false);
    }//GEN-LAST:event_btnrecCancelActionPerformed

    private void btnRecAnsQMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecAnsQMouseEntered
        btnRecAnsQ.setBackground(new Color(0, 125, 250));
        btnRecAnsQ.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnRecAnsQMouseEntered

    private void btnRecAnsQMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecAnsQMouseExited
       btnRecAnsQ.setBackground(new Color(255, 255, 255));
        btnRecAnsQ.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnRecAnsQMouseExited

    private void btnRecAnsQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecAnsQActionPerformed
        recoverSecAns.setVisible(true);
        recoverEmail.setVisible(false);
        selectOption.setVisible(false);
        resetPass.setVisible(false);
           
    }//GEN-LAST:event_btnRecAnsQActionPerformed

    private void btnRecEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecEmailMouseEntered
         btnRecEmail.setBackground(new Color(0, 125, 250));
        btnRecEmail.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnRecEmailMouseEntered

    private void btnRecEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecEmailMouseExited
       btnRecEmail.setBackground(new Color(255, 255, 255));
        btnRecEmail.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnRecEmailMouseExited

    private void btnRecEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecEmailActionPerformed
        recoverSecAns.setVisible(false);
        recoverEmail.setVisible(true);
        selectOption.setVisible(false);
        resetPass.setVisible(false);
    }//GEN-LAST:event_btnRecEmailActionPerformed

    private void chBoxShowPass4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBoxShowPass4ActionPerformed
       if (chBoxShowPass4.isSelected()) {
            txtUpdatePass.setEchoChar((char) 0);
        } else {
            txtUpdatePass.setEchoChar('*');
        }
    }//GEN-LAST:event_chBoxShowPass4ActionPerformed

    private void chBoxShowPass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBoxShowPass3ActionPerformed
       if (chBoxShowPass3.isSelected()) {
            txtROldPass.setEchoChar((char) 0);
        } else {
            txtROldPass.setEchoChar('*');
        }
    }//GEN-LAST:event_chBoxShowPass3ActionPerformed

    private void btnReqCode1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqCode1MouseEntered
        btnReqCode1.setBackground(new Color(0, 125, 250));
        btnReqCode1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnReqCode1MouseEntered

    private void btnReqCode1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqCode1MouseExited
        btnReqCode1.setBackground(new Color(255, 255, 255));
        btnReqCode1.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnReqCode1MouseExited

    private void btnReqCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqCode1ActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
         btnBack.setBackground(new Color(0, 125, 250));
         btnBack.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setBackground(new Color(255, 255, 255));
        btnBack.setForeground(new Color(101,101,101));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        recoverSecAns.setVisible(false);
        recoverEmail.setVisible(false);
        selectOption.setVisible(true);
        resetPass.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginOption;
    private javax.swing.JButton brnBackLogin;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackLogin;
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnMainWinL;
    private javax.swing.JButton btnMainWinR;
    private javax.swing.JButton btnMainWinS;
    private javax.swing.JButton btnRecAnsQ;
    private javax.swing.JButton btnRecEmail;
    private javax.swing.JButton btnRecover;
    private javax.swing.JButton btnReqCode;
    private javax.swing.JButton btnReqCode1;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton btnSignup1;
    private javax.swing.JButton btnrecCancel;
    private javax.swing.JButton btnrecUpdate;
    private javax.swing.JButton btnsecQback;
    private javax.swing.JButton btnsecQconfirm;
    private javax.swing.JCheckBox chBoxShowPass1;
    private javax.swing.JCheckBox chBoxShowPass2;
    private javax.swing.JCheckBox chBoxShowPass3;
    private javax.swing.JCheckBox chBoxShowPass4;
    private javax.swing.JCheckBox chBoxShowPassRecover;
    private javax.swing.JComboBox<String> cmbClassName;
    private javax.swing.JComboBox<String> cmbRecQ;
    private javax.swing.JComboBox<String> cmbSecQues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel login;
    private javax.swing.JPanel recover;
    private javax.swing.JPanel recoverEmail;
    private javax.swing.JPanel recoverSecAns;
    private javax.swing.JPanel resetPass;
    private javax.swing.JPanel selectOption;
    private javax.swing.JPanel signup;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtREmail;
    private javax.swing.JPasswordField txtROldPass;
    private javax.swing.JPasswordField txtRecA;
    private javax.swing.JTextField txtRecID;
    private javax.swing.JPasswordField txtSecurityAnswer;
    private javax.swing.JPasswordField txtUpdatePass;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel welcome;
    // End of variables declaration//GEN-END:variables
}
